"""added isPublic in rooms

Revision ID: 8aec1d6d5eb2
Revises: ed88a4301aa5
Create Date: 2022-10-27 17:35:44.854342

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8aec1d6d5eb2'
down_revision = 'ed88a4301aa5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rooms', sa.Column('isPublic', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rooms', 'isPublic')
    # ### end Alembic commands ###
