"""added membership_status in members table

Revision ID: e105284310a9
Revises: 8aec1d6d5eb2
Create Date: 2022-10-28 17:25:29.872723

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = 'e105284310a9'
down_revision = '8aec1d6d5eb2'
branch_labels = None
depends_on = None


def upgrade():
    memberstatus = postgresql.ENUM('pending', 'member', 'deleted', name='memberstatus')


    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('members', sa.Column('membership_status', memberstatus, nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('members', 'membership_status')
    # ### end Alembic commands ###
