"""added and deleted columns from gamemoves tablee

Revision ID: 4a52c3bd2485
Revises: d39b15c51f8c
Create Date: 2022-11-04 03:01:18.484798

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a52c3bd2485'
down_revision = 'd39b15c51f8c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game_moves', sa.Column('payload', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'rooms', type_='foreignkey')
    op.drop_column('game_moves', 'payload')
    # ### end Alembic commands ###
